### ISSUE TITLE
Background Drawable Error when rendering Expansion Panel on first time (API 23 and 29)

### ISSUE THREAD

**Issue by pedroaugustofr** [natura-cosmeticos/natds-android#120]
**Describe the bug**
The first time the Expansion Panel instance is rendered on Android using API 23 or 29 it doesn't recognize the `android:background="@drawable/ds_expansion_panel_border_collapsed"` property when in Dark mode Theme

**To Reproduce**
1. Go to an emulator or device using API 23 or 29 and make sure darkmode is ON in Expansion Panel Activity
2. Click on the Expansion Panel
4. See the background is wrong but afte rinteracting with the component it starts to render corrently because the background is changed via code using `container.setBackgroundResource(R.drawable.ds_expansion_panel_border_collapsed)`

**Expected behavior**
Expect the component to be rendered with the same style after interaction with it.

**Desktop (please complete the following information):**
 - OS: macOS Catalina
 - Android API 23 and Android API 29

**Additional context**
Workaround solution: 
- call the following method in the init function wafter inflating the component: `container.setBackgroundResource(R.drawable.ds_expansion_panel_border_collapsed)`

**Comment by mlcsouza** [comment]
@pedroaugustofr Thank you for reporting this issue.
Our team will analyze it, and as soon as we have news, we will keep you updated here 😄
