### ISSUE TITLE
Wrong font and spacing for buttons

### ISSUE THREAD

**Issue by dbnaza** [natura-cosmeticos/natds-android#88]
When using outlined button, it's necessary to add font to textAppearence, otherwise the font and spacing are incorrect.

![Screenshot_1592426068](https://user-images.githubusercontent.com/20612013/85053404-d1a61f00-b170-11ea-859c-b4679d8a8fe8.png)

Steps to reproduce on MiNegocio 
login -> open navigationDrawer -> select "Indicators" 

Expected behavior:
![Screenshot_1592423943](https://user-images.githubusercontent.com/20612013/85053476-ebdffd00-b170-11ea-9bc9-ba86bc7e362a.png)

 - OS: Android 
 - Version 0.5.0

**Comment by jimmyandrade** [comment]
Thank you for reporting this issue. Our team will analyze it, and as soon as we have news, we will update you here :)

**Comment by jimmyandrade** [comment]
> When using outlined button, it's necessary to add font to textAppearence, otherwise the font and spacing are incorrect.

Thank you for reporting this issue. Our team will analyze it, and as soon as we have news, we will update you here :)
